# Generated by Django 3.2.4 on 2021-07-07 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0003_auto_20210707_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message',
            field=models.TextField(default='None'),
        ),
    ]
